units:
  # create switch dimensions from Kailh Choc
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 5
  # Parts
  trackpad_radius: 20
  enc_radius: 11
  encx: 22
  ency: 22
  diode_x: 5
  diode_y: -8.75
  diode_right_rotate: 180
  diode_left_rotate: 180
  led_pos_x: 0 # Led X position relative to the switch center
  led_pos_y: 4.7 # Led Y position relative to the switch center
  led_rotation: 0 # Led rotation
  # Cases/Outlines variables
  dpx: px+4
  dpy: py+4
  screwRadius: 1
  standoffRadius: 2.5
  $default_padding: 19
  $default_spread: 19
  $default_width: 18
  $default_height: 17

points:
  zones:
    matrix:
      mirror: &mirror
        ref: matrix_inner_top
        distance: 2kx
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]
        rotate: -28
      columns:
        pinky:
          key:
            column_net: C1
            mirror.column_net: C10
          rows:
            top.key:
              led_prev: LED
              led_next: LED_1
            home.key:
              led_prev: LED_1
              led_next: LED_2
            bottom.key:
              led_prev: LED_2
              led_next: LED_3
            top.mirror.key:
              led_prev: LED_35
              led_next: LED_36
            home.mirror.key:
              led_prev: LED_34
              led_next: LED_35
            bottom.mirror.key:
              led_prev: LED_33
              led_next: LED_34
        ring:
          key:
            column_net: C2
            mirror.column_net: C9
            origin: [-12, -19]
            stagger: 12
          rows:
            top.key:
              led_prev: LED_5
              led_next: LED_6
            home.key:
              led_prev: LED_4
              led_next: LED_5
            bottom.key:
              led_prev: LED_3
              led_next: LED_4
            top.mirror.key:
              led_prev: LED_30
              led_next: LED_31
            home.mirror.key:
              led_prev: LED_31
              led_next: LED_32
            bottom.mirror.key:
              led_prev: LED_32
              led_next: LED_33
        middle:
          key:
            column_net: C3
            mirror.column_net: C8
            stagger: 9
          rows:
            top.key:
              led_prev: LED_6
              led_next: LED_7
            home.key:
              led_prev: LED_7
              led_next: LED_8
            bottom.key:
              led_prev: LED_8
              led_next: LED_9
            top.mirror.key:
              led_prev: LED_29
              led_next: LED_30
            home.mirror.key:
              led_prev: LED_28
              led_next: LED_29
            bottom.mirror.key:
              led_prev: LED_27
              led_next: LED_28
        index:
          key:
            column_net: C4
            mirror.column_net: C7
            stagger: -10
          rows:
            top.key:
              led_prev: LED_11
              led_next: LED_12
            home.key:
              led_prev: LED_10
              led_next: LED_11
            bottom.key:
              led_prev: LED_9
              led_next: LED_10
            top.mirror.key:
              led_prev: LED_24
              led_next: LED_25
            home.mirror.key:
              led_prev: LED_25
              led_next: LED_26
            bottom.mirror.key:
              led_prev: LED_26
              led_next: LED_27
        inner:
          key:
            column_net: C5
            mirror.column_net: C6
            stagger: -4
          rows:
            top.key:
              led_prev: LED_12
              led_next: LED_13
            home.key:
              led_prev: LED_13
              led_next: LED_14
            bottom.key:
              led_prev: LED_14
              led_next: LED_15
            top.mirror.key:
              led_prev: LED_23
              led_next: LED_24
            home.mirror.key:
              led_prev: LED_22
              led_next: LED_23
            bottom.mirror.key:
              led_prev: LED_21
              led_next: LED_22
      rows:
        bottom:
          row_net: R3
        home:
          row_net: R2
        top:
          row_net: R1

    thumbs:
      mirror: &mirror
        ref: matrix_inner_top
        distance: 2kx
      anchor:
        ref: matrix_inner_bottom
        shift: [-7, -u]
      columns:
        near:
          key:
            column_net: C3
            mirror.column_net: C8
          rows:
            home.key:
              led_prev: LED_15
              led_next: LED_16         
            home.mirror.key:
              led_prev: LED_20
              led_next: LED_21
        mid:
          key:
            column_net: C4
            mirror.column_net: C7
          key.spread: 21.25
          key.splay: -28
          key.origin: [-11, -9]
          rows:
            home.key:
              led_prev: LED_16
              led_next: LED_17         
            home.mirror.key:
              led_prev: LED_19
              led_next: LED_20
        far:
          key:
            column_net: C5
            mirror.column_net: C6
          key.spread: 21.25
          key.splay: -28
          key.origin: [-11, -9]
          rows:
            home.key:
              led_prev: LED_17
              led_next: LED_18         
            home.mirror.key:
              led_prev: LED_18
              led_next: LED_19         
      rows.home.row_net: R4

    # Components
    enc:
      mirror: &mirror
        ref: matrix_inner_top
        distance: 2kx
      key:
        tags:
        - part
        - enc
        #name: enc
        width: encx
        height: ency
      anchor:
        ref: matrix_middle_bottom
        shift: [0, -u -7]
      columns.enc.key.column_net: C2
      columns.enc.key.mirror.column_net: C9
      rows.enc.row_net: R4
    trackpad:
      key:
        tags:
        - part
        - trackpad
        name: trackpad
        width: encx
        height: ency
      anchor:
        ref: matrix_inner_bottom
        shift: [32, 16]

outlines:
  keys:
    - what: rectangle
      where: /(matrix|thumbs)_/
      size: [kx, ky]
  encoders:
    - what: circle
      where: enc
      radius: .85ky
  xlencoders:
    - what: circle
      where: enc
      radius: .85ky+2
  encs:
    - what: circle
      where: enc
      radius: enc_radius
  trackpad:
    - what: circle
      where: trackpad
      radius: trackpad_radius
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: matrix_inner_top
          shift: [0px,0.8py]
        - ref: mirror_matrix_inner_top
          shift: [0px,0.8py]
        - ref: mirror_matrix_middle_top
          shift: [0.5px,0.5py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5px,0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.5px,-0.2py]
        - ref: mirror_enc_enc_enc
          shift: [.9px,-0.2py]
        - ref: mirror_thumbs_near_home
          shift: [-0.5px,-.3py]
        - ref: mirror_thumbs_near_home
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbs_mid_home
          shift: [-0.5px,-0.5py]
        - ref: mirror_thumbs_mid_home
          shift: [0.5px,-0.5py]
        - ref: mirror_thumbs_far_home
          shift: [0.5px,-0.5py]
        - ref: mirror_thumbs_far_home
          shift: [0.5px,0.5py]
        - ref: thumbs_far_home
          shift: [0.5px,0.5py]
        - ref: thumbs_far_home
          shift: [0.5px,-0.5py]
        - ref: thumbs_mid_home
          shift: [0.5px,-0.5py]
        - ref: thumbs_mid_home
          shift: [-0.5px,-0.5py]
        - ref: thumbs_near_home
          shift: [-0.5px,-0.5py]
        - ref: thumbs_near_home
          shift: [-0.5px,-.3py]
        - ref: enc_enc_enc
          shift: [.9px,-0.2py]
        - ref: matrix_pinky_bottom
          shift: [0.5px,-0.2py]
        - ref: matrix_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px,-0.5py]
        - ref: matrix_pinky_top
          shift: [-0.5px,0.5py]
  xlboard:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_pinky_top
          shift: [-0.5dpx,0.5dpy-1]
        - ref: matrix_ring_top
          shift: [-0.5dpx,0.5dpy-.5]
        - ref: matrix_middle_top
          shift: [-0.5dpx+2,0.5dpy+.5]
        - ref: matrix_middle_top
          shift: [0.5dpx,0.5dpy]
        - ref: matrix_inner_top
          shift: [0dpx,0.8dpy-.5]
        - ref: mirror_matrix_inner_top
          shift: [0dpx,0.8dpy-.5]
        - ref: mirror_matrix_middle_top
          shift: [0.5dpx,0.5dpy]
        - ref: mirror_matrix_middle_top
          shift: [-0.5dpx+2,0.5dpy+.5]
        - ref: mirror_matrix_ring_top
          shift: [-0.5dpx,0.5dpy-.5]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5dpx,0.5dpy-1]
        - ref: mirror_matrix_pinky_bottom
          shift: [-0.5dpx,-0.5dpy]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.5dpx,-0.5dpy]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.5dpx,-0.2dpy-1.5]
        - ref: mirror_enc_enc_enc
          shift: [.9dpx-5,-0.2dpy-1]
        - ref: mirror_thumbs_near_home
          shift: [-0.5dpx,-.3dpy]
        - ref: mirror_thumbs_near_home
          shift: [-0.5dpx,-0.5dpy]
        - ref: mirror_thumbs_mid_home
          shift: [-0.5dpx+3,-0.5dpy]
        - ref: mirror_thumbs_mid_home
          shift: [0.5dpx-2,-0.5dpy]
        - ref: mirror_thumbs_far_home
          shift: [0.5dpx,-0.5dpy]
        - ref: mirror_thumbs_far_home
          shift: [0.5dpx,0.5dpy]
        - ref: thumbs_far_home
          shift: [0.5dpx,0.5dpy]
        - ref: thumbs_far_home
          shift: [0.5dpx,-0.5dpy]
        - ref: thumbs_mid_home
          shift: [0.5dpx-2,-0.5dpy]
        - ref: thumbs_mid_home
          shift: [-0.5dpx+3,-0.5dpy]
        - ref: thumbs_near_home
          shift: [-0.5dpx,-0.5dpy]
        - ref: thumbs_near_home
          shift: [-0.5dpx,-.3dpy]
        - ref: enc_enc_enc
          shift: [.9dpx-5,-0.2dpy-1]
        - ref: matrix_pinky_bottom
          shift: [0.5dpx,-0.2dpy-1.5]
        - ref: matrix_pinky_bottom
          shift: [0.5dpx,-0.5dpy]
        - ref: matrix_pinky_bottom
          shift: [-0.5dpx,-0.5dpy]
        - ref: matrix_pinky_top
          shift: [-0.5dpx,0.5dpy-1]
  full:
    - name: board
    - operation: add
      name: encoders
  xlfull:
    - name: xlboard
    - operation: add
      name: xlencoders
  fullstack:
    - name: xlfull
    - operation: stack
      name: full
  combo:
    - name: full
    - operation: subtract
      name: keys
    - operation: subtract
      name: encs
    - operation: subtract
      name: trackpad
  standoff:
    - what: circle
      radius: standoffRadius
      where: /matrix_pinky_top/
      adjust:
        shift: [kx/2-2, .6ky]
    - what: circle
      radius: standoffRadius
      where: /matrix_index_home/
      adjust:
        shift: [.5kx+.5, .33ky]
    - what: circle
      radius: standoffRadius
      where: /matrix_pinky_bottom/
      adjust:
        shift: [kx, .15ky]
    - what: circle
      radius: standoffRadius
      where: /matrix_index_bottom/
      adjust:
        shift: [.4kx, -.6ky]
  mounting:
    - what: circle
      radius: screwRadius
      where: /matrix_pinky_top/
      adjust:
        shift: [kx/2-2, .6ky]
    - what: circle
      radius: screwRadius
      where: /matrix_index_home/
      adjust:
        shift: [.5kx+.5, .33ky]
    - what: circle
      radius: screwRadius
      where: /matrix_pinky_bottom/
      adjust:
        shift: [kx, .15ky]
    - what: circle
      radius: screwRadius
      where: /matrix_index_bottom/
      adjust:
        shift: [.4kx, -.6ky]
pcbs:
  DeeDee:
    template: kicad8
    outlines:
      main:
        outline: full
    footprints:
      mount_hole_ring_top:
        what: ceoloide/mounting_hole_plated
        where: /matrix_ring_top/
        adjust:
          shift: [-.5u, -.5u]
      mount_hole_inner_top:
        what: ceoloide/mounting_hole_plated
        where: /matrix_inner_top/
        adjust:
          shift: [-.5u, -.5u]
      mount_hole_ring_bottom:
        what: ceoloide/mounting_hole_plated
        where: /matrix_ring_bottom/
        adjust:
          shift: [-.5u, -.5u]
      mount_hole_inner_bottom:
        what: ceoloide/mounting_hole_plated
        where: /matrix_inner_bottom/
        adjust:
          shift: [-.5u, -.5u]
      mount_hole_mid_home:
        what: ceoloide/mounting_hole_plated
        where: /thumbs_mid_home/
        adjust:
          shift: [.7u, 0]
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: /(matrix|thumbs)_/
        params:
          show_keycaps: true
          show_corner_marks: true
          keycaps_x: 19
          keycaps_y: 19
          from: "{{colrow}}"
          to: "{{column_net}}"
        adjust:
          rotate: 180
      diodes_left:
        what: ceoloide/diode_tht_sod123
        where: /^(matrix|thumbs)_/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: diode_left_rotate
          shift: [diode_x, diode_y]
      diodes_enc_left:
        what: ceoloide/diode_tht_sod123
        where: /^enc_/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: 90
          shift: [-5, 1]
      diodes_right:
        what: ceoloide/diode_tht_sod123
        where: /^(mirror_matrix|mirror_thumbs)_/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: diode_right_rotate
          shift: [-diode_x, diode_y]
      diodes_enc_right:
        what: ceoloide/diode_tht_sod123
        where: /^(mirror_enc)_/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: 270
          shift: [-5, -4]
      enc_left:
        what: rotary
        where.ref: enc_enc_enc
        where.rotate: 180
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          A: ELA
          B: ELB
          C: GND
      enc_right:
        what: rotary
        where.ref: mirror_enc_enc_enc
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          A: ERA
          B: ERB
          C: GND
      nicenano:
        what: ceoloide/mcu_nice_nano
        params:
          reverse_mount: true
          include_extra_pins: true
          use_rectangular_jumpers: true
          invert_jumpers_position: true
          # left side(when flipped)
          #RAW:
          #GND:
          #RST:
          #VCC:
          P21: LED
          P20: C1
          P19: C2
          P18: C3
          P15: C4
          P14: C5
          P16: ELA # Encoder left A
          P10: ELB # Encoder left B

          # right side (when flipped)
          P1: C10
          P0: C9
          P2: SDA
          P3: SCL
          P4: C8
          P5: C7
          P6: C6
          P7: R1
          P8: ERA # Encoder right A
          P9: ERB # Encoder Right B

          P101: R2
          P102: R3
          P107: R4
        #where:
        #  ref.aggregate.parts: [matrix_inner_home, mirror_matrix_inner_home]
        #  shift: [0,-7]
        #  rotate: 0
        where:
          ref.aggregate.parts: [matrix_inner_bottom, mirror_matrix_inner_bottom]
          rotate: 0

      cirque_trackpad:
        what: simisimis/trackpad_cirque_40mm
        params:
          P9: SCL
          P10: SDA
          P11: GND
          P12: VCC
        where:
          ref.aggregate.parts: [matrix_inner_bottom, mirror_matrix_inner_bottom]
          shift: [13, 0]
          rotate: 90

      oled:
        what: simisimis/ssd1306_64x48
        params:
          P1: SCL
          P2: SDA
          P3: GND
          P4: VCC
        where:
          ref.aggregate.parts: [matrix_inner_bottom, mirror_matrix_inner_bottom]
          rotate: 0

      leds_left_side:
        what: ceoloide/led_sk6812mini-e
        where: /^(matrix|thumbs)_/
        params:
          P1: VCC
          P2: "{{key.led_next}}" #DOUT
          P3: GND
          P4: "{{key.led_prev}}" #DIN
        adjust:
          shift: [led_pos_x, led_pos_y]
          rotate: led_rotation
      leds_right_side:
        what: ceoloide/led_sk6812mini-e
        where: /^(mirror_matrix|mirror_thumbs)_/
        params:
          P1: VCC
          P2: "{{mirror.key.led_next}}" #DOUT
          P3: GND
          P4: "{{mirror.key.led_prev}}" #DIN
        adjust:
          shift: [led_pos_x, led_pos_y]
          rotate: led_rotation

cases:
  bottom:
    - name: full
      extrude: 1
  xlbottom:
    - name: xlfull
      extrude: 1
  _outerWall:
    - name: xlfull
      extrude: 4
  _innerWall:
    - name: full
      extrude: 4
  _holes:
    - name: mounting
      extrude: 4
  _standoffs:
    - name: standoff
      extrude: 4
  wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
  case:
    - what: case
      name: xlbottom
      operation: add
    - what: case
      name: wall
      operation: add
